### ISSUE TITLE
[1.0.2] Update messed up icons

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-theme-quark#10]
After the update to Quark 1.0.2 from Quark 1.0.1 and clearing the cache, all icons are messed up.
Example:
![icon](https://user-images.githubusercontent.com/15226809/36634023-64baebb8-19d9-11e8-986f-0c7b9c952dba.png)

**Comment by rhukster** [comment]
What is the HTML of that code you have there?

**Comment by kiranetph** [comment]
```
<a href="/user/pages/01.patches/manual/Maintenance.zip">
  <p title="<i class='fa fa-download'></i>" alt="" class="btn circle btn-purple">
    <i class="fa fa-download"></i>
  </p>
</a>
```
I can easily replicate the problem. If i use Quark v1.0.1, the icon displays properly. After update to Quark v1.0.2 and a clean browser cache, the wrong icon displays. 
Going back to Quark v1.0.1 and a clean browser cache displays the correct icon.

**Comment by kiranetph** [comment]
The problem was triggered by template (still processing the v1.0.1 base.html.twig) inheritance and the changed asset name from (v1.0.1)
```
{% do assets.addCss('theme://css/line-awesome-font-awesome.min.css') %}
```
to (v1.02)
```
{% do assets.addCss('theme://css/line-awesome.min.css') %}
```
Issue can be closed.
