### ISSUE TITLE
Missing metadata include

### ISSUE THREAD

**Issue by stephenvoisey** [getgrav/grav-theme-quark#12]
Quick one. Within the base template, an include:

`{% include 'partials/metadata.html.twig' %}`

But no such file exists in partials or elsewhere.

**Comment by rhukster** [comment]
That is in the Grav core now.. under `system/templates/partials/`

**Comment by rhukster** [comment]
BTW, this was moved there because it's useful for all themes, and rarely needs changing.  You can of course override it in your theme, but don't need to provide it yourself now.

**Comment by stephenvoisey** [comment]
Thanks for the clarification, many thanks!
