### ISSUE TITLE
Change favicon in v2.0.2

### ISSUE THREAD

**Issue by fUE4** [getgrav/grav-theme-quark#171]
Don't know if its an update issue, but after updating GRAV to v1.6.28 and QUARK to v2.0.2 recently, the favicon in ``grav.quark/user/themes/quark/images/logo/favicon.png`` doesn't show up anymore. Instead the GRAV favicon is displayed. Any suggestions?

Thanks for help,
Frank

**Comment by rhukster** [comment]
Are you using an 'untouched' version of quark or a modified one?

Quark uses: `<link rel="icon" type="image/png" href="{{ url('theme://images/favicon.png') }}" />` for the link to the favicon so just put your favicon in the `user/themes/quark/images/` folder.  This is where the default Grav favicon is. just replace it. 

BTW you should not be using a raw version of Quark and then updating it.  You should probably make a copy (with devtools) or at least extend it. That will allow you to make changes and still update.

**Comment by fUE4** [comment]
Thanks for replying!
It's now in the right folder `user/themes/quark/images/` but the Grav favicon still overrides it. Any further suggestions?

**Comment by rhukster** [comment]
if you have physically replaced the file then it's just cached.  My suggestion is to create your own copy of Quark with devtools:

```
bin/gpm install devtools
bin/plugin devtools new-theme
```

Then pick copy option, and select `quark`. This will create a new theme that is a copy of your current quark theme.  Then you can make changes in there such as pointing to a different location for favicon, plus any other changes you want without having to worry about accidentally updating quark and overriding your changes.

**Comment by fUE4** [comment]
Works fine now, thank you!
