### ISSUE TITLE
fa-firefox and fa-cc-paypal wrong ??

### ISSUE THREAD

**Issue by jodumont** [getgrav/grav-theme-quark#18]
such as an example fa-firefox show linkedin icons
now I compared this [css](https://raw.githubusercontent.com/getgrav/grav-theme-quark/develop/css/line-awesome.min.css) with that [chart](https://fontawesome.com/icons?d=gallery&m=free)
and the unicode (f269) for firefox seams ok!

![screenshot_2018-04-09_09-42-29](https://user-images.githubusercontent.com/5204724/38485878-9ae6d6a6-3bdb-11e8-9c4b-b0709b00ba0b.png)

note : **fa-cc-paypal** also appear different as expected.

**Comment by rhukster** [comment]
Looks like an issue with LineAwesome - https://github.com/icons8/line-awesome

Probably need to raise an issue there.

**Comment by jodumont** [comment]
I did thanks for your time and your upstream ;)

https://github.com/icons8/line-awesome/issues/13
