### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by asiftyro** [getgrav/grav-theme-quark#185]
File Missing?

https://github.com/getgrav/grav-theme-quark/blob/32d516569f69ac8f6ab66b16ece193091b7a954e/templates/modular/gallery.html.twig#L69

**Comment by mahagr** [comment]
I think that the file comes from a plugin. You need to have it installed. That said, I'm not 100% sure which plugin.

**Comment by rhukster** [comment]
its to support the Lightbox Gallery premium plugin: https://getgrav.org/premium/lightbox-gallery

You can only use this modular type if you have purchased the Lightbox Gallery plugin.

**Comment by asiftyro** [comment]
Thanks for the infor @mahagr and @rhukster
