### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by Pumpapa** [getgrav/grav-theme-quark#195]
In the README it says "logo via the YAML". Which Yaml is that? Site, or system, assuming it is in user/config.

**Comment by rhukster** [comment]
The quark.yaml. In admin simply go to themes/quark and change the setting and save. Without admin copy user/themes/quark/quark.yaml to user/config/themes/ and edit it there.

**Comment by Pumpapa** [comment]
Thanks! I also meant to update the docs to avoid other having to solve this. But for me this worked. Thanks!
