### ISSUE TITLE
reason for production-mode option

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-theme-quark#20]
Just a driveby observation, I haven't used this theme.

What is the purpose of the `production-mode` option I noticed in the theme blueprint, since this is available using more standard generic Grav options (environment configs, caching/minifying/pipelining etc) ?

**Comment by rhukster** [comment]
Quark is using gulp for scss and it's easy enough to generate minified version during this process.  So it's a nice way to get things minified rather than having to have Grav do it. Options are good!

**Comment by hughbris** [comment]
Thanks for the answer.

> Options are good!

Ooh, not always! They can easily confuse and mislead.

So which one takes precedence? I think this should be documented.
