### ISSUE TITLE
Footer and hero misaligned in IE11

### ISSUE THREAD

**Issue by ChocolatePinecone** [getgrav/grav-theme-quark#21]
While testing in IE11 some elements (hero and footer) are misaligned when opened in IE11.

Tested with IE v11.2125.14393.0
![quark ie11 issue](https://user-images.githubusercontent.com/25863930/38627029-3b3e32a6-3dae-11e8-8782-cb854aaf1a8d.PNG)

**Comment by thedavidgay** [comment]
I am experiencing the same footer behavior in IE 11.
The footer is stuck to the top of the page, as in the screenshot.

**Comment by thedavidgay** [comment]
The footer issue was completely resolved for me by the change in #11.

**Comment by rhukster** [comment]
Need to find another solution, as #11 breaks the sticky footer (which is default).

**Comment by rhukster** [comment]
Ok, found a proper fix.

**Comment by ChocolatePinecone** [comment]
The footer problem is solved, but the top text is still misaligned.
Can this issue be opened again?
