### ISSUE TITLE
[W3C validator] "Duplicate id" if you use the same modular template several times

### ISSUE THREAD

**Issue by SylvainMoingeon** [getgrav/grav-theme-quark#24]
Hello,

Modulars template begins with  `<section id="modular-xxx" >`.

If you want to use the same template for different sections in your modular page, you get "Duplicate Id" error on W3C validator.

**Comment by rhukster** [comment]
I've fixed this, but it might mean broken CSS until you hard-refresh as i had to change all `#modular-X` references to `.modular-X`
