### ISSUE TITLE
Custom CSS?

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-theme-quark#26]
I would like to apply custom CSS in Quark. Is there a way to do it?  The existing `custom.css` file seems to have no effect.

**Comment by paulhibbitts** [comment]
Hi @ThosG , I just tested adding the following to the default custom.css file in Quark and it seemed to work-ok, maybe a Browser refresh issue?

```
body a {
    color: #CC0000;
}
```

Let me know if that works for you too.
Paul

**Comment by ThosG** [comment]
@paulhibbitts 
> maybe a Browser refresh issue?
Doh. Thanks Paul. So simple.
