### ISSUE TITLE
Hero Text and homepage not responsive

### ISSUE THREAD

**Issue by kreativmind** [getgrav/grav-theme-quark#28]
I have entered my text using the markdown for the home page and the text doesn't fit inside the mobile area. I have to scroll left to right to read it all. It appears that the menu icon is way outside to the right of the hero image and causing the issue. Anyone experience this?
![20180521_112408](https://user-images.githubusercontent.com/484151/40318286-b9490c0c-5ce9-11e8-8585-d1c37da30729.jpg)

**Comment by rhukster** [comment]
Fixed in develop
