### ISSUE TITLE
Constant section ids in modular templates generate duplicate element ids

### ISSUE THREAD

**Issue by tremel** [getgrav/grav-theme-quark#43]
In theme `modular/text.html` and `modular/features.html.twig` the section ids are "modular-text" and "modular-features". If used twice on a modular page the ids are duplicated. Example is "modular-features" twice in [https://demo.getgrav.org/onepage-skeleton/](https://demo.getgrav.org/onepage-skeleton/). By the way: `#top` is also duplicated on this page.

**Comment by SylvainMoingeon** [comment]
Hello, see issue #24 . ;-)

**Comment by tremel** [comment]
Duplicate of #24
