### ISSUE TITLE
Why testing 'page.header.continue_link' before including comments plugin

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-theme-quark#45]
Quark (and Enigma) have the following code in '[partials/blog-item.html.twig](https://github.com/getgrav/grav-theme-quark/blob/e57aac7667088e2c99723b2e3f7a79c150bb8636/templates/partials/blog-item.html.twig#L18)'
```
{% if page.header.continue_link is sameas(true) and config.plugins.comments.enabled %}
   {% include 'partials/comments.html.twig' %}
{% endif %}
```
What purpose serves testing 'page.header.continue_link' before adding the comments plugin needed?

I cannot find any documentation on the use of 'continue_link' both here as on 'learn'

**Comment by rhukster** [comment]
Seems this was a missing option in blog item blueprint. I've added it now.

**Comment by pamtbaau** [comment]
@rhukster Comming back to this issue because a user is stumbling over the problem that the Comments plugin is not included in blog items...

Again, why is `page.header.continue_link is same as(true)` used to test if the Comments plugin should be included or not. The value is only of any value in 'templates/partials/blog/title.html.twig'.

As a side question: What is the 'Daring Fireball style title link'? Google doesn't return any link looking like the one that is created when `link` and `continue_link` are set in frontmatter.
