### ISSUE TITLE
logo is not auto-scaled?

### ISSUE THREAD

**Issue by Rikusen0335** [getgrav/grav-theme-quark#51]
I'm using .svg file to my blog logo, but the logo is going original size.
If is there any settings or solutions, please tell me.

**Comment by rhukster** [comment]
please upload your SVG so i can test with it.

**Comment by Rikusen0335** [comment]
Okay, this is it.
https://drive.google.com/file/d/1DMwrsTP5ZtGhuT4uj6p1sBI7I2n-IfqK/view?usp=sharing
(I'm sorry for using Google Drive because GitHub is not support .svg)

**Comment by rhukster** [comment]
works for me: https://trilby.d.pr/p8RORA

Maybe you need to hard-refresh your browser cache to pick up the new CSS ???

**Comment by Rikusen0335** [comment]
It works for me after hard-refreshing!
Thanks anyway.
