### ISSUE TITLE
grav.user.username is empty

### ISSUE THREAD

**Issue by nixhol** [getgrav/grav-theme-quark#52]
It seems the variable `grav.user.username` is empty.
When I dump`(grav.user.username)` or `{{ grav.user.username }}` it, I see nothing.
I know I am logged in because I can see the user array in the `$_SESSION` variable

The problem seems to occur with others as well, see for example:
[https://discourse.getgrav.org/t/if-config-plugins-login-enabled-and-grav-user-username-not-working/6769](https://discourse.getgrav.org/t/if-config-plugins-login-enabled-and-grav-user-username-not-working/6769)

Grav 1.5.1
Login 2.7.3

Edit: My user array is good when I am in the admin section, but not when I am in the front website.

**Comment by mahagr** [comment]
Doesn't look like issue -- in the link user hasn't been logged into the frontend.

**Comment by nixhol** [comment]
you are right sorry, I thought when you logged in admin, you were logged in site as well...

**Comment by bonnebulle** [comment]
Just for comment, this can help
So, Grav slipt admin_login and front-end_login ?
How do I login into front-end ?
If you dont know how you can disable this feature :
```> Admin > Configuration > System >> Session >>> Session Split => OFF```
( /admin/config/system )
Source: https://discourse.getgrav.org/t/is-it-possible-to-login-in-admin-and-frontend-at-the-same-time/7313/5
