### ISSUE TITLE
Missing simplesearch_searchbox template

### ISSUE THREAD

**Issue by loranger** [getgrav/grav-theme-quark#53]
Hello, I just installed a brand new grav with the [Blog skeleton](https://github.com/getgrav/grav-skeleton-blog-site) and activated Quark, but it seems an template is missing:

```
 Server Error

Sorry, something went terribly wrong!
400 - Template "partials/simplesearch_searchbox.html.twig" is not defined in "partials/sidebar.html.twig" at line 6.
```

Did I miss something ?

**Comment by rhukster** [comment]
Simple search plugin? It’s part of the dependencies for this skeleton. If you. Installed from github you should run `bin/grav install` to install them.

**Comment by loranger** [comment]
It was definitely the part I missed.
Thank you so much @rhukster ! 👍
