### ISSUE TITLE
svg logo

### ISSUE THREAD

**Issue by zaszlo** [getgrav/grav-theme-quark#54]
The logo can be changed by putting a file in the images/logo directory and calling it from the theme's yaml file, like:
```
custom_logo:
  -
    name: xyz.svg
```
The problem is that this renders the svg inside an image tag, not as on the demo page with plain svg embed, so having a black&white svg like in the demo wont be switched when having light or dark background... I think the solution would be to render svg's in the way it is in the demo. Tried to override this by removing the custom_logo part and by naming my logo to grav-logo.svg and putting it to my active theme's images folder but it keeps reading the default grav-logo.svg from the parent (quark) theme's image directory.
Replacing the grav-logo.svg inside quark theme solves the problem... until the next update.

Anyone else faced it/solved this?

**Comment by rhukster** [comment]
That's the way to do it :)
