### ISSUE TITLE
Select if a modular content is displayed on menu or not

### ISSUE THREAD

**Issue by DominiqueVial** [getgrav/grav-theme-quark#56]
Is there a way to choose for a modular content to be displayed or not in the menu? Currently it is always displayed in the menu.

**Comment by sebasvisser** [comment]
As far as I know, there isn't. Although I think that having a space ( " " ) as the menu name, works close enough at the moment.
so
`menu: 
`

**Comment by ganar** [comment]
@DominiqueVial I did not find a way of doing it: I ended up hiding the menu item with CSS

**Comment by rhukster** [comment]
This has been fixed and will be in the next release:

```
visible: false
```
