### ISSUE TITLE
Deprecated issues in navigation.html.twig

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav-theme-quark#58]
In the new deprecated section, there are issues relating to Quark, something like
`calling 'nav_loop' is deprecated since 1.28` in `partials/navigation.html.twig`.

> By the way, I'm using Firefox, and I cannot figure out how to copy a message in Debugbar. Clicking only opens and closes a div. So I had to copy out the text above. 

nav_loop is defined as a macro in navigation. Are all macros deprecated? What is meant by 'deprecated since 1.28'? Grav 1.28?

I am uncertain whether any of the 'deprecated' notices are related to my code or to standard Quark.

**Comment by rhukster** [comment]
These issues have been addressed in the 2.0 beta release which is intended for use with Grav 1.6
