### ISSUE TITLE
Fontawesome update?

### ISSUE THREAD

**Issue by marcocevoli** [getgrav/grav-theme-quark#60]
Would it be possible to update the Font Awesome version used by Quark theme?

**Comment by rhukster** [comment]
Font Awesome 5.0 is not 100% compatible with 4.7.  Even with the extra compatibility shims i've had problems.  Frankly, i think the increased 'bloat' from 5.0 is just not worthwhile.  We can't use anything but the default widths with the free version anyway.

**Comment by B-Interactive** [comment]
@rhukster, I know it's been a long time, but are you able to recall where you had problems with version 5 + shims?  This would help me try to replicate the issues in 6.4.0.
