### ISSUE TITLE
Extract footer to separate partial twig

### ISSUE THREAD

**Issue by esocode** [getgrav/grav-theme-quark#62]
Currently the site footer is contained in `base.html.twig`. That makes it difficult to modify the footer in themes that inherit from Quark because it would either require to copy and modify `base.html.twig`, thus decoupling it from future Quark updates, or to copy and modify page templates like `default.html.twig` which would require the replication of code in all pages. 

This could be avoided if Quark imported it's default footer twig with `{% include 'partials/footer.html.twig' %} ` which could then be overridden by inheriting themes.

**Comment by rhukster** [comment]
Done for next release
