### ISSUE TITLE
400 - Template "blog_item.html.twig" is not defined.

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav-theme-quark#66]
Getting this error when visiting Blog item using latest Quark

![screen shot 2018-10-23 at 7 58 44 pm](https://user-images.githubusercontent.com/5002814/47399495-43109e80-d6fe-11e8-8a5d-b8dd420e8879.jpg)

**Comment by rhukster** [comment]
Blog item pages should be `item.md` which would use the `item.html.twig` template. `item.html.twig` does actually include `partials/blog-item.html.twig` - https://github.com/getgrav/grav-theme-quark/blob/develop/templates/partials/blog-item.html.twig

I think you are using Quark with a skeleton that was built for another theme.

**Comment by simmonsr** [comment]
Yes, I see when I switch from Gantry template to Quark I don't have option to blog_item. Cheers
