### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by katsil** [getgrav/grav-theme-quark#73]
Hello. thank you for creating such a cool theme
I would like to ask if you ever plan to create a dark theme? I would really like to embed this on the site

thank you for your response

**Comment by rhukster** [comment]
Just create a new theme from Quark and customize it to make it dark.  Quark is supposed to be used as a base to build other themes.

**Comment by greensam88** [comment]
I know this isn't perfect, but a decent start for a dark theme:
I just added these lines of code to `custom.css`
```
#body-wrapper {
	background-color: #323232;
	color: white;
}

.card {
	background-color: black;
}

h1, h2, h3, h4, h5, h6 {
	color: white;
}

#header {
	background-color: #000000;
}

#header a {
	color: white;
	background-color: #000000;
}

.label.label-primary {
	color: white;
	background-color: #323232;
}

.label.label-secondary {
	color: white;
	background-color: #999999;
}

#footer {
	background-color: #000000 !important;
}
```
