### ISSUE TITLE
Do not use !important in scss

### ISSUE THREAD

**Issue by yurkobb** [getgrav/grav-theme-quark#8]
I've noticed there's a number of `!important` rules in the theme scss, which makes overriding some things via custom.css, like the active menu link color, a pain. If there is a place for `!important`, I think it should be only used in `custom.css` / child themes to force-customize stuff.

```
$ grep '!important' --recursive theme
scss/theme/_header.scss:25:      color: rgba($light-color, 0.7) !important;
scss/theme/_header.scss:28:      color: $light-color !important;
scss/theme/_header.scss:31:        color: $dark-color !important;
scss/theme/_header.scss:44:    //border-bottom: 0 !important;
scss/theme/_menu.scss:22:          color: $dropmenu-hover-text !important;
scss/theme/_framework.scss:73:    font-size: 4rem !important;
scss/theme/_framework.scss:78:    font-size: 2.5rem !important;
scss/theme/_framework.scss:82:    margin-top: -45px !important;
scss/theme/_mobile.scss:149:        color: $primary-color-light !important;
scss/theme/_typography.scss:27:  outline: none !important;
scss/theme/_typography.scss:40:    padding: 1rem !important;
scss/theme/_typography.scss:51:  padding: 1rem !important;
````

**Comment by rhukster** [comment]
If you want to make changes, simply do it in the SCSS variables for the colors and rebuild the CSS with `gulp`.

**Comment by yurkobb** [comment]
Thanks, that's one of the ways around it for sure, and probably a better way that using `custom.css`, if the change has to be made globally. However, if one wants to only make a small change in one specific case, it's still better not to force the users to rebuild the whole theme css if they only need a small and quick change.

So I would say that SCSS variables and `custom.css` are not mutually exclusive - they both have a use case.

The use of `!imporatant` in the theme makes the customization harder and sometimes counter intuitive, not only via `custom.css`, but also in SCSS, if the changes are more nuanced (say, different colors on different types of pages).

**Comment by rhukster** [comment]
the `!important` is only used where it's really needed.  Usually this is in dropdown menus where **not using it** is going to actually make the scss more complex and require many more lines of code.

You know you can still override a `!important` anyway, just make your custom.css more specific and also include a `!important`.

**Comment by stevenjaycohen** [comment]
> If you want to make changes, simply do it in the SCSS variables for the colors and rebuild the CSS with `gulp`.

There are situations where one cannot access gulp. Please consider mere mortals at the mercy of locked down hosting (like Hostgator for example). Leave removing the !important markers from CSS as a Feature Request or put it on the Roadmap. I promise to look through the code to see if they can be avoided.
