### ISSUE TITLE
Menu don't show in modular page

### ISSUE THREAD

**Issue by andrekutianski** [getgrav/grav-theme-quark#91]
When I create a modular page the main menu are not displayed inside de modular page, Instead is showing the module folder name.

I'm doing any miss configuration or this is the suspected behavior?

**Default home page and menu**
![](https://i.imgur.com/zD1YBmi.jpg)

**Inside of a modular page**
![](https://i.imgur.com/GViOmUS.jpg)

**Comment by paulmassen** [comment]
On this page, you can add in expert mode:

`onpage_menu: false`

this will disable the "one-page menu" and enable the regular menu
