### ISSUE TITLE
Inherited theme : make it possible to customize specific blocks from base.html.twig

### ISSUE THREAD

**Issue by aoloe** [getgrav/grav-theme-quark#95]
When building a theme that _inherits_ Quark, I think there's no clean way to customise a specific block of the base template.

This is also an issue with Antimatter.

Somebody opened a ticket for Antimatter:

https://github.com/getgrav/grav-theme-antimatter/issues/97

and even made a pull request:

https://github.com/getgrav/grav-theme-antimatter/pull/100

which has been left  uncommented.

Please, refer to the original ticket for the reasons behind this request.

**Comment by Karmalakas** [comment]
Just ran into the same issue. Thanks @luuuke

**Comment by rhukster** [comment]
@luuuke 's solution is elegant. I recommend this approach!

**Comment by Karmalakas** [comment]
This might be added to documentation. Maybe to recipes section?

**Comment by rhukster** [comment]
The docs are fully open to user submissions of this type.  I would gladly accept a PR that provided this approach.

**Comment by aoloe** [comment]
@rhukster i understand your position, but i don't feel like -- at this point -- closing this ticket was the right action.

indeed, one way to solve this ticket is to accept a PR that adds the snippet above to the docs.
but there is no such PR, so i consider that grav/quark still does not have an easy (or non trivial but documented) way to inherit block and the issue is still there.

please, consider reopening this ticket.

**Comment by Karmalakas** [comment]
[Here you go](https://github.com/getgrav/grav-learn/pull/888) :)

**Comment by aoloe** [comment]
thanks @Karmalakas !
